trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: UseNode@2
    inputs:
      versionSpec: '16.x'
      checkLatest: true

  - script: npm install
    displayName: 'Install Dependencies'

  - script: npm test
    displayName: 'Run Tests'

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(System.DefaultWorkingDirectory)'
      ArtifactName: 'drop'

